version: '3.6'
services:
  postgresql:
    image: postgres:10.4-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:3.6.3
    ports:
      - "27017:27017"
  employee-service:
    image: edrb/employee-service
    ports:
      - "8080:8080"
    environment:
      PG_HOST: postgresql
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - postgresql
      - rabbitmq
  event-service:
    image: edrb/event-service
    ports:
     - "8081:8081"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATA_MONGODB_HOST: mongodb
    depends_on:
      - mongodb
      - rabbitmq
